# Generated by Django 4.2.2 on 2025-02-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=255, unique=True)),
                ('entity_type', models.CharField(choices=[('mine_owner', 'Mine Owner/Operator'), ('exploration', 'Exploration Company'), ('drilling', 'Drilling Service Provider'), ('equipment', 'Equipment Manufacturer')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GeospatialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Unknown', max_length=255)),
                ('site_name', models.CharField(default='Unknown', max_length=255)),
                ('site_type', models.CharField(default='Unknown', max_length=255)),
                ('ortho', models.FileField(blank=True, null=True, upload_to='geospatial/ortho/')),
                ('dem', models.FileField(blank=True, null=True, upload_to='geospatial/dem/')),
                ('stockpile_geojson', models.FileField(blank=True, null=True, upload_to='geospatial/stokpilegeojson/')),
                ('model_3d_ply', models.FileField(blank=True, null=True, upload_to='geospatial/3dmodel/')),
                ('object_3d', models.FileField(blank=True, null=True, upload_to='geospatial/3dobject/')),
                ('tin_ply', models.FileField(blank=True, null=True, upload_to='geospatial/tin/')),
                ('pit_boundary_geojson', models.FileField(blank=True, null=True, upload_to='geospatial/pitboundry/')),
                ('dem_boundary_geojson', models.FileField(blank=True, null=True, upload_to='geospatial/demboundry/')),
                ('rainfall_data', models.FileField(blank=True, null=True, upload_to='geospatial/rainfall/')),
                ('soil_raster', models.FileField(blank=True, null=True, upload_to='geospatial/soilraster/')),
                ('water_depth', models.FileField(blank=True, null=True, upload_to='geospatial/waterdepth/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='geospatial_data', to='analytics.entity')),
            ],
        ),
    ]
