# Generated by Django 4.2.2 on 2024-09-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataengineer', '0002_imagemodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
