# Generated by Django 4.2.2 on 2024-11-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataengineer', '0003_alter_imagemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='file_size',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
