# Generated by Django 4.2.2 on 2025-02-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataengineer', '0005_projectmodel_imagemodel_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='model',
            new_name='project',
        ),
    ]
