# Generated by Django 4.2.2 on 2024-05-25 06:19

import common.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, null=True)),
                ('company_name', models.CharField(max_length=120)),
                ('drone_description', models.TextField(blank=True, null=True)),
                ('droneid', models.CharField(default='none', max_length=250)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=models.SET(common.models.get_sentinel_user), related_name='%(class)s_created_by_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=models.SET(common.models.get_sentinel_user), related_name='%(class)s_modified_by_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
