# Generated by Django 4.2.2 on 2024-05-25 06:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drones', '0002_rename_job_drones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drones',
            new_name='Drone',
        ),
    ]
