# Generated by Django 4.2.2 on 2024-05-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0004_drone_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
