# Generated by Django 4.2.2 on 2024-05-27 11:39

import common.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drones', '0005_drone_live'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_ts', models.DateTimeField(auto_now=True, null=True)),
                ('droneid', models.CharField(max_length=223)),
                ('time', models.CharField(max_length=128)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=models.SET(common.models.get_sentinel_user), related_name='%(class)s_created_by_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=models.SET(common.models.get_sentinel_user), related_name='%(class)s_modified_by_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
