# Generated by Django 4.2.2 on 2024-06-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0006_dronedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronedata',
            name='FileField',
            field=models.FileField(default='null', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='dronedata',
            name='time',
            field=models.DateTimeField(max_length=128),
        ),
    ]
